# Generated by Django 4.2.27 on 2026-01-14 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cart_order_payment_cancellation_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='customer_id',
            field=models.CharField(default='anonymous', help_text="Customer ID or 'anonymous'", max_length=255, unique=True),
        ),
    ]
