# Generated by Django 4.2.27 on 2026-01-14 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_cart_unique_together_alter_cart_customer_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(help_text='Unique product identifier', max_length=255, unique=True)),
                ('name', models.CharField(help_text='Product display name', max_length=255)),
                ('price', models.DecimalField(decimal_places=2, help_text='Product price', max_digits=10)),
                ('description', models.TextField(blank=True, help_text='Product description', null=True)),
                ('category', models.CharField(blank=True, help_text='Product category', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether product is available')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'name'],
                'indexes': [models.Index(fields=['product_id'], name='core_produc_product_811b5d_idx'), models.Index(fields=['is_active'], name='core_produc_is_acti_1d1aa8_idx')],
            },
        ),
    ]
