# Generated by Django 4.2.27 on 2026-01-15 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_cart_unique_together_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('booking', 'Booking'), ('cancellation', 'Cancellation'), ('payment', 'Payment'), ('conversation', 'Conversation')], help_text='Type of activity', max_length=50)),
                ('action', models.CharField(help_text='Human-readable description of the activity', max_length=255)),
                ('customer_id', models.CharField(blank=True, help_text='Customer identifier', max_length=255, null=True)),
                ('customer_name', models.CharField(blank=True, help_text='Customer name', max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional context data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['activity_type', '-created_at'], name='core_activi_activit_84f18c_idx'), models.Index(fields=['-created_at'], name='core_activi_created_3d0bd9_idx')],
            },
        ),
    ]
