# Generated by Django 4.2.27 on 2026-01-15 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_delivery_address_to_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='name',
            field=models.CharField(default='', help_text='Product name', max_length=255),
            preserve_default=False,
        ),
    ]
