# Generated by Django 4.2.27 on 2026-01-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_name_to_cartitem_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_id',
            field=models.CharField(blank=True, help_text='Canonical customer ID (user.id)', max_length=255, null=True),
        ),
    ]
