# Generated by Django 4.2.27 on 2026-01-14 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('voice', 'Voice Call'), ('sms', 'SMS')], max_length=10)),
                ('phone_number', models.CharField(max_length=20)),
                ('messages', models.JSONField(default=list)),
                ('intent', models.CharField(blank=True, max_length=50, null=True)),
                ('conversation_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='core.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
